"""add max_length constraints to database models

Revision ID: 3843c3eb8bcf
Revises: 31e8ba379790
Create Date: 2025-08-26 10:48:12.831401+08:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3843c3eb8bcf"
down_revision: Union[str, Sequence[str], None] = "31e8ba379790"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
