"""Initial migration

Revision ID: 31e8ba379790
Revises:
Create Date: 2025-08-25 10:18:42.650606+08:00

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "31e8ba379790"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "face_recognition_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("enable", sa.Boolean(), nullable=True),
        sa.Column("set_mode", sa.Boolean(), nullable=True),
        sa.Column("enable_blink_detection", sa.Boolean(), nullable=True),
        sa.Column("dlib_predictor_path", sa.String(), nullable=True),
        sa.Column("dlib_recognition_model_path", sa.String(), nullable=True),
        sa.Column("face_model", sa.String(), nullable=True),
        sa.Column("minimum_bounding_box_height", sa.Float(), nullable=True),
        sa.Column("minimum_face_detection_score", sa.Float(), nullable=True),
        sa.Column("eyes_detection_brightness_threshold", sa.Integer(), nullable=True),
        sa.Column("eyes_detection_brightness_value_min", sa.Integer(), nullable=True),
        sa.Column("eyes_detection_brightness_value_max", sa.Integer(), nullable=True),
        sa.Column("sensitivity", sa.Float(), nullable=True),
        sa.Column("consecutive_prediction_intervals_frame", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_face_recognition_config_id"), "face_recognition_config", ["id"], unique=False)
    op.create_table(
        "system_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("debug", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_system_config_id"), "system_config", ["id"], unique=False)
    op.create_table(
        "system_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("group", sa.String(), nullable=False),
        sa.Column("log_level", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_system_logs_id"), "system_logs", ["id"], unique=False)
    op.create_table(
        "video_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rtsp", sa.String(), nullable=True),
        sa.Column("web_camera", sa.Integer(), nullable=True),
        sa.Column("image_height", sa.Integer(), nullable=True),
        sa.Column("image_width", sa.Integer(), nullable=True),
        sa.Column("detection_range_start_point_x", sa.Integer(), nullable=True),
        sa.Column("detection_range_start_point_y", sa.Integer(), nullable=True),
        sa.Column("detection_range_end_point_x", sa.Integer(), nullable=True),
        sa.Column("detection_range_end_point_y", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_video_config_id"), "video_config", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_video_config_id"), table_name="video_config")
    op.drop_table("video_config")
    op.drop_index(op.f("ix_system_logs_id"), table_name="system_logs")
    op.drop_table("system_logs")
    op.drop_index(op.f("ix_system_config_id"), table_name="system_config")
    op.drop_table("system_config")
    op.drop_index(op.f("ix_face_recognition_config_id"), table_name="face_recognition_config")
    op.drop_table("face_recognition_config")
    # ### end Alembic commands ###
